#!/usr/bin/env bun
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const PKG_ROOT = path.resolve(import.meta.dir, '..');
const GEN_DIR = path.join(PKG_ROOT, '.gen');

function findWebDist(): string {
  const candidates = [path.join(PKG_ROOT, 'web-dist'), path.resolve(PKG_ROOT, '..', 'web', 'dist')];
  for (const dir of candidates) {
    if (existsSync(path.join(dir, 'index.html'))) return dir;
  }
  throw new Error(`web build output not found, run \`pnpm build\` first (looked in ${candidates.join(', ')})`);
}

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir).sort()) {
    const abs = path.join(dir, entry);
    if (statSync(abs).isDirectory()) walk(abs, out);
    else out.push(abs);
  }
  return out;
}

const dist = findWebDist();
const files = walk(dist);
if (files.length === 0) throw new Error(`no files under ${dist}`);

const specifier = (abs: string) => {
  const rel = path.relative(GEN_DIR, abs).split(path.sep).join('/');
  return rel.startsWith('.') ? rel : `./${rel}`;
};
const key = (abs: string) => path.relative(dist, abs).split(path.sep).join('/');

const lines = [
  '// Generated by scripts/gen-assets.ts — do not edit.',
  "import { setEmbeddedAssets } from '../src/assets.ts';",
  ...files.map((f, i) => `import f${i} from ${JSON.stringify(specifier(f))} with { type: 'file' };`),
  '',
  'setEmbeddedAssets({',
  ...files.map((f, i) => `  ${JSON.stringify(key(f))}: f${i},`),
  '});',
  '',
];

mkdirSync(GEN_DIR, { recursive: true });
writeFileSync(path.join(GEN_DIR, 'assets.ts'), lines.join('\n'));
writeFileSync(
  path.join(GEN_DIR, 'entry.ts'),
  ['// Generated by scripts/gen-assets.ts — do not edit.', "import './assets.ts';", "import '../src/cli.ts';", ''].join('\n'),
);

console.log(`embedded ${files.length} files from ${path.relative(PKG_ROOT, dist)}`);
